[package]
name = "home_finance"
version = "0.1.0"
authors = ["AndrejKlim <tydysch@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.18.1" }
chrono = {version = "0.4.19"}